node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "/opt/emqx/data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

dashboard {
  listeners.http {
    bind = 18083
  }
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  max_connections = 512000
  ssl_options {
    keyfile  = "/opt/emqx/ssl/private/server-key.pem"
    certfile = "/opt/emqx/ssl/certs/server-cert.pem"
  }
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  max_connections = 1024000
}

listeners.wss.default {
  bind = "0.0.0.0:8084"
  max_connections = 512000
  ssl_options {
    keyfile  = "/opt/emqx/ssl/private/server-key.pem"
    certfile = "/opt/emqx/ssl/certs/server-cert.pem"
  }
}

authentication = [
  {
    mechanism = password_based
    backend = mysql
    enable = true

    server = "MYSQL_SERVER_PLACEHOLDER"
    username = "MYSQL_USER_PLACEHOLDER"
    password = "MYSQL_PASS_PLACEHOLDER"
    database = "MYSQL_DB_PLACEHOLDER"

    query = "SELECT password AS password_hash FROM mqtt_user WHERE username = ${username} LIMIT 1"
    query_timeout = "5s"

    password_hash_algorithm {
      name = sha256
      salt_position = disable
    }
  }
]

authorization {
  no_match = deny
  deny_action = ignore
  cache {
    enable = false
  }
  sources = [
    {
      type = mysql
      enable = true

      server = "MYSQL_SERVER_PLACEHOLDER"
      username = "MYSQL_USER_PLACEHOLDER"
      password = "MYSQL_PASS_PLACEHOLDER"
      database = "MYSQL_DB_PLACEHOLDER"

      query = "SELECT IF(allow=1,'allow','deny') AS permission, TRIM(LEADING 'eq ' FROM topic) AS topic, CASE access WHEN 1 THEN 'subscribe' WHEN 2 THEN 'publish' ELSE 'all' END AS action FROM mqtt_acl WHERE (username = ${username} OR username = '$all') ORDER BY username DESC, id ASC"
    }
  ]
}

retainer {
  enable = true
  backend {
    type = built_in_database
    storage_type = disc
    max_retained_messages = 0
  }
}

mqtt {
  max_qos_allowed = 2
  retain_available = true
  mqueue_store_qos0 = false
  max_mqueue_len = 10000
}
